apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: charts.bitnami.com/bitnami
    targetRevision: 18.2.2
    path: ""
    chart: nginx
    helm:
      values: >-
        initContainers:
          - name: set-delay
            image: alpine
            command: ['sh', '-c', 'sleep 60 && echo "creating dir"']
  destination:
    server: https://kubernetes.default.svc
    namespace: my-frontend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true 
  
